#! /bin/bash

echo "Insert the icon in theme Mint-Y..."
mkdir -p /usr/share/icons/Mint-Y/mimetypes/scalable
cp text-x-tml.svg /usr/share/icons/Mint-Y/mimetypes/scalable

echo "Add search directory to index..."
sed -i 's/Directories=/Directories=mimetypes/scalable,/' /usr/share/icons/Mint-Y/index.theme

echo "Insert to index definition stanza..."

# i.e.
# ###################
# 
# [mimetypes/scalable]
# Size=16
# Context=Mimetypes
# Type=Scalable
# MinSize=8
# MaxSize=512
#
# ###########

sed -i 's/###########/###################\n\n[mimetypes/scalable\nSize=16\nContext=Mimetypes\nType=Scalable\nMinSize=8\nMaxSize=512\n\n###########/' /usr/share/icons/Mint-Y/index.theme


echo "Update gtk icon cache..."
gtk-update-icon-cache /path/to/the/theme/folder

echo "Done."
